server.port=8090
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
logging.level.com.integra.mysigncore=DEBUG
#Other properties
hibernate.config.file.path=hibernate.cfg.xml
docuexec.properties=docuexec.properties
kafka.config.url=http://127.0.0.1:9092
kafka.producer.url=http://127.0.0.1:9090/msgproducer